# Generated by Django 5.1 on 2025-08-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('parent', 'folder_name_hash')},
        ),
    ]
