# Generated by Django 5.1 on 2025-08-30 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_folder_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='files_ai_proc_52ee0a_idx',
        ),
        migrations.RemoveField(
            model_name='ainode',
            name='total_users',
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('folder', 'file_name_hash')},
        ),
        migrations.RemoveField(
            model_name='folder',
            name='ai_processing_status',
        ),
        migrations.AddField(
            model_name='ainode',
            name='own_user_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_node', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driveuser',
            name='whole_context_ai_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='file',
            name='ai_processing_status',
        ),
    ]
