# Generated by Django 5.1 on 2025-09-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_documentchunk_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
