# Generated by Django 5.1 on 2025-08-27 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_file_user_alter_folder_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.TextField(help_text='RSA public key derived from seed phrase', unique=True)),
                ('storage_used', models.BigIntegerField(default=0, help_text='Storage used in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('preferred_ai_node', models.ForeignKey(blank=True, help_text="DriveUser's preferred AI node for queries", null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ainode')),
            ],
            options={
                'db_table': 'drive_users',
            },
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.driveuser'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='api.driveuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
