version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app  # Mount the backend directory
    ports:
      - "8000:8000"  # Expose Django on port 8000
    depends_on:
      - minio
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=thedrive
      - MINIO_ENDPOINT=http://minio:9000  # MinIO inside the container
      - MINIO_SECURE=False
    networks:
      - minio-network

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_WEB_UI=true   # Enable the web UI on port 9000
    ports:
      - "9000:9000"  # MinIO Web UI on port 9000
      - "9001:9001"  # MinIO Console UI (optional)
    volumes:
      - minio-data:/data  # MinIO persistent storage
    command: server --console-address ":9001" /data
    networks:
      - minio-network

volumes:
  minio-data:
    driver: local

networks:
  minio-network:
    driver: bridge
